spring:
  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: s1.iocoder.cn:8848 # Nacos 服务器地址
        namespace: test # Nacos 命名空间

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    address: spring-cloud://s1.iocoder.cn:8848 # 指定 Dubbo 服务注册中心的地址
