# es
spring:
  application:
    name: search-application
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: s1.iocoder.cn:9300
      repositories:
        enable: true
  elasticsearch:
    rest:
      uris: s1.iocoder.cn:9200

  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: s1.iocoder.cn:8848 # Nacos 服务器地址

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    address: spring-cloud://s1.iocoder.cn:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: admin-application, order-application, product-application # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 提供者的协议
  protocol:
    name: dubbo
    port: -1
  # Dubbo 提供服务的扫描基础包
  scan:
    base-packages: cn.iocoder.mall.search.biz.service
  # Dubbo 服务提供者的配置
  provider:
    filter: -exception
    ProductSearchService:
      version: 1.0.0
  consumer:
    ProductSpuService:
      version: 1.0.0
    ProductCategoryService:
      version: 1.0.0
    CartService:
      version: 1.0.0

# rocketmq
rocketmq:
  name-server: s1.iocoder.cn:9876
  producer:
    group: search-producer-group
